name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dependencies
        run: lein deps

      - name: tests & coverage
        run: lein cloverage --codecov

      - name: eastwood
        run: lein eastwood

      - name: cljfmt
        run: lein cljfmt check

      - name: kibit
        run: lein kibit

      - name: send coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)
